### ISSUE TITLE
TO-DO List

### ISSUE THREAD

**Issue by Irgendwer01** [Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded#14]
- [x] Rework Quests (https://github.com/Infinity-Evolved-Reloaded-Modpacks/Infinity-Evolved-Reloaded/pull/13)
- [x] Make no Alloys Craftable (see pic above)
- [x] Replace Carpenters Blocks through Blockcraftery

**Comment by Irgendwer01** [comment]
![grafik](https://user-images.githubusercontent.com/67506320/93334715-ab525700-f825-11ea-953b-25c9d1fe0fe3.png
